name: touristic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gemini
  google_generative_ai: ^0.4.3

  # caching & storage
  shared_preferences: ^2.2.3
  floor: ^1.5.0

  # dependency injection
  get_it: ^7.7.0

  # bloc
  flutter_bloc: ^8.1.6

  # ssh connection
  ssh2:
    path: C:\Users\smudg\OneDrive\Desktop\flutter_ssh2-master

  # google maps
  google_maps_flutter: ^2.7.0

  # widgets
  flutter_svg: ^2.0.10+1
  avatar_glow: ^3.0.1

  # helpers
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  package_info_plus: ^8.0.0
  mime: ^1.0.5
  image_picker: ^1.1.2

  # servics
  speech_to_text: ^6.6.0
  path_provider: ^2.1.3
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/maps/theme/
    - assets/maps/style/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf

    - family: Noto
      fonts:
        - asset: assets/fonts/noto_sans_black.ttf
          weight: 900
        - asset: assets/fonts/noto_sans_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans_extra_light.ttf
          weight: 200
        - asset: assets/fonts/noto_sans_thin.ttf
          weight: 100